spring.application.name=orderflow

spring.datasource.url=jdbc:postgresql://localhost:5433/orderflow
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true

app.jwt.secret=9a4f98e7885b54c8a245f8e6b12c85d7b9a5f6e8c4d2b1a3e5f7a9d0c8b6a4f2